compatibility_date = "2026-01-10"

# D1 binding (para wrangler y para referencia)
[[d1_databases]]
binding = "DB"
database_name = "cazeexchange_db"
database_id = "75deabea-11ae-4eaa-9713-3abd54267fdd"
migrations_dir = "migrations"
